---
name: CICD

# manual click (deliver) workflow whenever user needs
on:
  workflow_dispatch:

jobs:
# every job need separate runner, parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone form github"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "docker container built"

  test:
    needs: [build,code]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "testing the container"

  deploy:
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploying the app
        run: echo "docker compose deployed the app"
  
    
    
