# workflow name
---
name: Hello workflow

# runs on a trigger
on: 
  workflow_dispatch:
  #push:
  #  branches: [main]

# jobs inside the workflow

jobs:
  greet:
  # this is github runner, each job runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello Kapil"
      - name: say hello to user
        run: echo "hello $USER"
  
  # new job needs new runner
  details:
    runs-on: ubuntu-latest
    steps:
      - name: versions of docker, python, etc
        run: docker --version && python --version
